---
title: "ARM"
author: "Jack Piccione"
date: "10/14/2021"
output: html_document
---

```{r}
#install.packages("arules")
#install.packages("TSP")
#install.packages("data.table")
#install.packages("arulesViz", dependencies = TRUE)
#install.packages("sp")
#install.packages("dplyr", dependencies = TRUE)
#install.packages("purrr", dependencies = TRUE)
#install.packages("devtools", dependencies = TRUE)
library(arules)
library(TSP)
library(arulesViz)
library(sp)
library(devtools)
library(networkD3)
library(visNetwork)
```


```{r}
library(viridisLite)
library(viridis)
library(TSP)
library(data.table)
#library(ggplot2)
#library(Matrix)
#library(tcltk)
library(dplyr)
library(devtools)
library(purrr)
library(tidyr)
library(stringr)
library(stringdist)
library(ggplot2)
```



```{r}
IMDb<-read.csv("/Users/jackpiccione/Google Drive/IMDb_Final (1).csv")

IMDb = subset(IMDb, select = -c(X,Rank,Runtime,Rating,Metascore,Votes, Director,Actor, Gross))

genres = unique(unlist(str_split(IMDb$Genre,",")))

genres

for(genre in genres){
  IMDb[str_c(genre)] = ifelse(( str_detect(IMDb$Genre,genre) | str_detect(IMDb$Genre,"no genres") ) , genre , "")
}


IMDb = subset(IMDb, select = -c(Title,Genre))


write.csv(IMDb,"transactionData_dup.csv",row.names = FALSE)
csv2<-read.csv("/Users/jackpiccione/Google Drive/transactionData_dup.csv")
#get rid of duplicate cols
IMDb <- csv2 %>% select(-contains("X."))
#write.csv(IMDb,"transactionData_noTitles.csv",row.names = FALSE)
```


```{r }
genres <- read.transactions("/Users/jackpiccione/Google Drive/transactionData_noTitles.csv",
                           rm.duplicates = TRUE, 
                           format = "basket",  ##if you use "single" also use cols=c(1,2)
                           sep=",",  ## csv file
                           cols=NULL) ## The dataset HAS row numbers
#inspect(genres)

##### Use apriori to get the RULES
G_rules = arules::apriori(genres, parameter = list(support=.01, 
                                                 confidence=.5, minlen=2))
inspect(G_rules)
```
```{r}
## Convert the RULES to a DATAFRAME
Rules_DF<-DATAFRAME(G_rules, separate = TRUE)
(head(Rules_DF))
str(Rules_DF)
## Convert to char
Rules_DF$LHS<-as.character(Rules_DF$LHS)
Rules_DF$RHS<-as.character(Rules_DF$RHS)

## Remove all {}
Rules_DF[] <- lapply(Rules_DF, gsub, pattern='[{]', replacement='')
Rules_DF[] <- lapply(Rules_DF, gsub, pattern='[}]', replacement='')

head(Rules_DF)

##rules as DF
Rules_Lift<-Rules_DF[c(1,2,6)]
Rules_Conf<-Rules_DF[c(1,2,4)]
Rules_Sup<-Rules_DF[c(1,2,3)]

```

```{r}
#confidence rules
SortedRulesK <- sort(G_rules, by="confidence", decreasing=TRUE)
inspect(SortedRulesK[1:15])
subrulesK <- head(sort(SortedRulesK, by="confidence"),15)
#plot(subrulesK, main="Scatter Plot for 15 Confidence Rules")
plot(SortedRulesK[1:15],method='graph',shading='confidence',engine="igraph",main="Network of Confidence Rules")

Rules_Conf <- transform(Rules_Conf, confidence = as.numeric(confidence))

Rules_Confdes <- Rules_Conf[order(Rules_Conf$confidence,decreasing = TRUE),]
Rules_Confdes <- head(Rules_Confdes,15)
Rules_Confdes$rules <- paste(Rules_Confdes$LHS,"=>",Rules_Confdes$RHS)

ggplot(Rules_Confdes, aes(reorder(rules, -confidence), confidence)) +          
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Top 15 Confidence Rules")+
  theme(plot.title = element_text(hjust = 0.5))+
  xlab("rule")
```


```{r}
#lift rules
SortedRulesK <- sort(G_rules, by="lift", decreasing=TRUE)
inspect(SortedRulesK[1:15])
subrulesK <- head(sort(SortedRulesK, by="lift"),15)
#plot(subrulesK, main="Scatter Plot for 15 Lift Rules")
plot(SortedRulesK[1:15],method='graph',shading='lift',engine="igraph",main="Network of Lift Rules")

Rules_Lift <- transform(Rules_Lift, lift = as.numeric(lift))

Rules_Liftdes <- Rules_Lift[order(Rules_Lift$lift,decreasing = TRUE),]
Rules_Liftdes <- head(Rules_Liftdes,15)
Rules_Liftdes$rules <- paste(Rules_Liftdes$LHS,"=>",Rules_Liftdes$RHS)



ggplot(Rules_Liftdes, aes(reorder(rules, -lift), lift)) +          
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Top 15 Lift Rules")+
  theme(plot.title = element_text(hjust = 0.5))+
  xlab("rule")
```

```{r}
#support rules
SortedRulesK <- sort(G_rules, by="support", decreasing=TRUE)
inspect(SortedRulesK[1:15])
subrulesK <- head(sort(SortedRulesK, by="support"),15)
#plot(subrulesK, main="Scatter Plot for 15 Support Rules")
plot(SortedRulesK[1:15],method='graph',shading='support',engine="igraph",main="Network of Support Rules")

Rules_Sup <- transform(Rules_Sup, support = as.numeric(support))

Rules_Supdes <- Rules_Sup[order(Rules_Sup$support,decreasing = TRUE),]
Rules_Supdes <- head(Rules_Supdes,15)
Rules_Supdes$rules <- paste(Rules_Supdes$LHS,"=>",Rules_Supdes$RHS)

ggplot(Rules_Supdes, aes(reorder(rules, -support), support)) +          
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Top 15 Support Rules")+
  theme(plot.title = element_text(hjust = 0.5))+
  xlab("rule")
```

```{r}
## Convert the RULES to a DATAFRAME
Rules_DF2<-DATAFRAME(G_rules, separate = TRUE)
(head(Rules_DF2))
str(Rules_DF2)
## Convert to char
Rules_DF2$LHS<-as.character(Rules_DF2$LHS)
Rules_DF2$RHS<-as.character(Rules_DF2$RHS)

## Remove all {}
Rules_DF2[] <- lapply(Rules_DF2, gsub, pattern='[{]', replacement='')
Rules_DF2[] <- lapply(Rules_DF2, gsub, pattern='[}]', replacement='')

head(Rules_DF2)

## Other options for the following
Rules_Lift<-Rules_DF2[c(1,2,6)]
Rules_Conf<-Rules_DF2[c(1,2,4)]
Rules_Sup<-Rules_DF2[c(1,2,3)]
#names(Rules_Lift) <- c("SourceName", "TargetName", "Weight")
#names(Rules_Conf) <- c("SourceName", "TargetName", "Weight")
#head(Rules_Lift)
#head(Rules_Conf)

###########################################
###### Do for SUp, Conf, and Lift   #######
###########################################
## Remove the sup, conf, and count
## USING LIFT
Rules_L<-Rules_DF2[c(1,2,6)]
names(Rules_L) <- c("SourceName", "TargetName", "Weight")
head(Rules_L,30)

## USING SUP
Rules_S<-Rules_DF2[c(1,2,3)]
names(Rules_S) <- c("SourceName", "TargetName", "Weight")
head(Rules_S,30)

## USING CONF
Rules_C<-Rules_DF2[c(1,2,4)]
names(Rules_C) <- c("SourceName", "TargetName", "Weight")
head(Rules_C,30)

## CHoose and set
#Rules_Sup<-Rules_C
Rules_Sup<-Rules_L
#Rules_Sup<-Rules_S

###########################################################################
#############       Build a NetworkD3 edgeList and nodeList    ############
###########################################################################

#edgeList<-Rules_Sup
# Create a graph. Use simplyfy to ensure that there are no duplicated edges or self loops
#MyGraph <- igraph::simplify(igraph::graph.data.frame(edgeList, directed=TRUE))
#plot(MyGraph)

############################### BUILD THE NODES & EDGES ####################################
#rules based on lift 
(edgeList<-Rules_Sup)
MyGraph <- igraph::simplify(igraph::graph.data.frame(edgeList, directed=TRUE))

nodeList <- data.frame(ID = c(0:(igraph::vcount(MyGraph) - 1)), 
                       # because networkD3 library requires IDs to start at 0
                       nName = igraph::V(MyGraph)$name)
## Node Degree
(nodeList <- cbind(nodeList, nodeDegree=igraph::degree(MyGraph, 
                    v = igraph::V(MyGraph), mode = "all")))

## Betweenness
BetweenNess <- igraph::betweenness(MyGraph, 
      v = igraph::V(MyGraph), 
      directed = TRUE) 

(nodeList <- cbind(nodeList, nodeBetweenness=BetweenNess))

## This can change the BetweenNess value if needed
BetweenNess<-BetweenNess/100



## For scaling...divide by 
## RE:https://en.wikipedia.org/wiki/Betweenness_centrality
##/ ((igraph::vcount(MyGraph) - 1) * (igraph::vcount(MyGraph)-2))
## For undirected / 2)
## Min-Max Normalization
##BetweenNess.norm <- (BetweenNess - min(BetweenNess))/(max(BetweenNess) - min(BetweenNess))


## Node Degree


###################################################################################
########## BUILD THE EDGES #####################################################
#############################################################
# Recall that ... 
# edgeList<-Rules_Sup
getNodeID <- function(x){
  which(x == igraph::V(MyGraph)$name) - 1  #IDs start at 0
}
(getNodeID("elephants")) 

edgeList <- plyr::ddply(
  Rules_Sup, .variables = c("SourceName", "TargetName" , "Weight"), 
  function (x) data.frame(SourceID = getNodeID(x$SourceName), 
                          TargetID = getNodeID(x$TargetName)))

head(edgeList)
nrow(edgeList)

########################################################################
##############  Dice Sim ################################################
###########################################################################
#Calculate Dice similarities between all pairs of nodes
#The Dice similarity coefficient of two vertices is twice 
#the number of common neighbors divided by the sum of the degrees 
#of the vertices. Method dice calculates the pairwise Dice similarities 
#for some (or all) of the vertices. 
DiceSim <- igraph::similarity.dice(MyGraph, vids = igraph::V(MyGraph), mode = "all")
head(DiceSim)

#Create  data frame that contains the Dice similarity between any two vertices
F1 <- function(x) {data.frame(diceSim = DiceSim[x$SourceID +1, x$TargetID + 1])}
#Place a new column in edgeList with the Dice Sim
head(edgeList)
edgeList <- plyr::ddply(edgeList,
                        .variables=c("SourceName", "TargetName", "Weight", 
                                               "SourceID", "TargetID"), 
                        function(x) data.frame(F1(x)))
head(edgeList)

##################################################################################
##################   color #################################################
######################################################
COLOR_P <- colorRampPalette(c("#00FF00", "#FF0000"), 
                            bias = nrow(edgeList), space = "rgb", 
                            interpolate = "linear")
COLOR_P
(colCodes <- COLOR_P(length(unique(edgeList$diceSim))))
edges_col <- sapply(edgeList$diceSim, 
                    function(x) colCodes[which(sort(unique(edgeList$diceSim)) == x)])
nrow(edges_col)

## NetworkD3 Object
#https://www.rdocumentation.org/packages/networkD3/versions/0.4/topics/forceNetwork
#install.packages("networkD3")
library(networkD3)
D3_network_Tweets <- networkD3::forceNetwork(
  Links = edgeList, # data frame that contains info about edges
  Nodes = nodeList, # data frame that contains info about nodes
  Source = "SourceID", # ID of source node 
  Target = "TargetID", # ID of target node
  Value = "Weight", # value from the edge list (data frame) that will be used to value/weight relationship amongst nodes
  NodeID = "nName", # value from the node list (data frame) that contains node description we want to use (e.g., node name)
  Nodesize = "nodeBetweenness",  # value from the node list (data frame) that contains value we want to use for a node size
  Group = "nodeDegree",  # value from the node list (data frame) that contains value we want to use for node color
  height = 700, # Size of the plot (vertical)
  width = 900,  # Size of the plot (horizontal)
  fontSize = 20, # Font size
  linkDistance = networkD3::JS("function(d) { return d.value*10; }"), # Function to determine distance between any two nodes, uses variables already defined in forceNetwork function (not variables from a data frame)
  linkWidth = networkD3::JS("function(d) { return d.value/10; }"),# Function to determine link/edge thickness, uses variables already defined in forceNetwork function (not variables from a data frame)
  opacity = 0.9, # opacity
  zoom = TRUE, # ability to zoom when click on the node
  opacityNoHover = 0.9, # opacity of labels when static
  linkColour = "red"   ###"edges_col"red"# edge colors
) 

# Plot network
D3_network_Tweets
networkD3::saveNetwork(D3_network_Tweets, 
                       "NetD3_DCR2019_worldNewsL.html", selfcontained = TRUE)
```


```{r}
#VisNetwork
(edges2 <- data.frame(
  from = edgeList$SourceID, 
  to = edgeList$TargetID,
  # add labels on edges                  
  label = edgeList$Weight,
  # length
  #length = c(100,500),
  # width
  width = edgeList$Weight)
 # arrows
 #arrows = c("to", "from", "middle", "middle;to"),
 # dashes
 #dashes = c(TRUE, FALSE),
 # tooltip (html or character)
 #title = paste("Edge", 1:8),
 # smooth
 #smooth = c(FALSE, TRUE),
 # shadow
 #shadow = c(FALSE, TRUE, FALSE, TRUE)
) 


## Build the nodes
(nodes2 <- data.frame(id = nodeList$ID, label = nodeList$nName))

MyVis<-visNetwork(nodes2, edges2, height = "500px", width = "100%") %>% visNodes(color = list(background = "yellow", border = "blue"))

visSave(MyVis, file = "Vis_Network.html")

```

